### PR TITLE
.veb_expansion_cache

### LINKED ISSUE #199: [Bug]: [ERROR] [MY-010666] [Server] VillageSQL: 'Failed to load VEF extension 'vsql_complex': failed to load so: error 22
**Describe the bug**
Could be a minor issue or may not be a issue, but using the same datadir for both release and debug builds once I install an extension is not possible. I'm getting this error.

2026-04-06T15:55:03.934011Z 6 [System] [MY-010666] [Server] VillageSQL: 'Validating system schema...'
2026-04-06T15:55:03.940099Z 6 [System] [MY-010666] [Server] VillageSQL: 'System schema verification completed successfully'
2026-04-06T15:55:03.940354Z 6 [ERROR] [MY-010666] [Server] VillageSQL: 'Failed to load VEF extension 'vsql_complex': failed to load so: error 22 (..debug/lib/veb/_expanded/vsql_complex/4b19fe2dd27d19808f093d250fdca9f33de42d755ecae720e234a2f0228f5288/lib/vsql_complex.so: cannot open shared object file: No such file or directory)'
2026-04-06T15:55:03.940363Z 6 [ERROR] [MY-010666] [Server] VillageSQL: 'Extension loading failed'
2026-04-06T15:55:03.940490Z 0 [ERROR] [MY-010666] [Server] VillageSQL: 'Failed to initialize'
2026-04-06T15:55:03.940504Z 0 [ERROR] [MY-010119] [Server] Aborting
2026-04-06T15:55:05.516957Z 0 [System] [MY-010910] [Server] .../debug/runtime_output_directory/mysqld: Shutdown complete (mysqld 8.4.8-villagesql-0.0.4-dev-d72b7c55-debug)  Source distribution.

**To Reproduce**
1. Create a fresh datadir with release builds
2. Install the vsql_complex extension using INSTALL EXTENSION vsql_complex;
3. Shutdown the server
4. Restart with debug builds using the same datadir

The error pasted above is seen

Workaround : UNINSTALL the extension and the try, it works

**Expected behavior**
A user should be able to use the datadir both for release and debug builds

**Screenshots**

**Setup (please complete the following information):**

Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.4 LTS
Release:	24.04
Codename:	noble

commit: d72b7c552382864d4805ba6c9ef9a539e0b9c25a
date: 2026-04-03 09:02:14 +0200
created at: 2026-04-05 11:45:22Z
branch: main
MySQL source 8.4.8-villagesql-0.0.4-dev-d72b7c55
MySQL release maturity LTS

**Additional context**

### PR DESCRIPTION
**Pull request by dbentley-vsql**
## Description

Move the expasion cache into datadir.

Fixes #199 

extension_shared_veb_dir_restart which failed but now passes

## Checklist

- [x] I have signed the CLA
- [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] I have added or updated tests as appropriate
- [x] My changes maintain compatibility with upstream MySQL 8.4

### CODE REVIEW

File: villagesql/veb/veb_file.cc [hunk 1]
```diff
@@ -673,20 +707,20 @@ void cleanup_orphaned_expansion_directories(
...
+    LogVSQL(INFORMATION_LEVEL, "No .veb_expansion_cache directory found");
     return;
   }
 
-  // Open _expanded directory
+  // Open .veb_expansion_cache directory
   DIR *expanded_dir = opendir(expanded_base_path.c_str());
   if (!expanded_dir) {
-    LogVSQL(WARNING_LEVEL, "Failed to open _expanded directory");
+    LogVSQL(WARNING_LEVEL, "Failed to open .veb_expansion_cache directory");
```
Comment (malone-at-work) [inline villagesql/veb/veb_file.cc:726]: Can we log the actual path here

**Review by malone-at-work — COMMENTED** [review]
We didn't need to do anything to prevent innodb from doing anything to this directory?

**Review by malone-at-work — APPROVED** [review]
See comments I sent in previous.  No need to get me to re-review.

**Comment by dbentley-vsql** [comment]
> We didn't need to do anything to prevent innodb from doing anything to this directory?

FWIW, no: clone only looks at specific files and each .ibd file under here the path. And because this path is hidden, those won't be seen.
